package com.workify.communication.web.controller;

import com.workify.communication.domain.Message;
import com.workify.communication.domain.Note;
import com.workify.communication.repository.MessageRepository;
import com.workify.communication.repository.NoteRepository;
import com.workify.communication.service.NoteExtractionService;
import com.workify.communication.service.NoteExtractionService.ExtractedNote;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

@Slf4j
@RestController
@RequestMapping("/api/conversations")
@CrossOrigin(origins = "http://localhost:4200")
public class NoteController {

    @Autowired private NoteRepository noteRepository;
    @Autowired private MessageRepository messageRepository;
    @Autowired private NoteExtractionService extractionService;

    // ── GET all notes ────────────────────────────────────────────────────
    /** GET /api/conversations/{id}/notes?userId={userId} */
    @GetMapping("/{id}/notes")
    public ResponseEntity<List<Note>> getNotes(
            @PathVariable Long id,
            @RequestParam Long userId) {
        return ResponseEntity.ok(
                noteRepository.findByConversationIdAndUserIdOrderByCreatedAtAsc(id, userId));
    }

    // ── POST manual note ─────────────────────────────────────────────────
    /** POST /api/conversations/{id}/notes?userId={userId} */
    @PostMapping("/{id}/notes")
    public ResponseEntity<Note> createNote(
            @PathVariable Long id,
            @RequestParam Long userId,
            @RequestBody Map<String, String> body) {
        String content = body.get("content");
        if (content == null || content.isBlank()) return ResponseEntity.badRequest().build();
        Note note = Note.builder()
                .conversationId(id)
                .userId(userId)
                .content(content.trim())
                .isAutoGenerated(false)
                .build();
        return ResponseEntity.ok(noteRepository.save(note));
    }

    // ── PUT update note ──────────────────────────────────────────────────
    /** PUT /api/conversations/{id}/notes/{noteId} */
    @PutMapping("/{id}/notes/{noteId}")
    public ResponseEntity<Note> updateNote(
            @PathVariable Long id,
            @PathVariable Long noteId,
            @RequestBody Map<String, String> body) {
        String content = body.get("content");
        if (content == null || content.isBlank()) return ResponseEntity.badRequest().build();
        return noteRepository.findById(noteId)
                .filter(n -> n.getConversationId().equals(id))
                .map(n -> {
                    n.setContent(content.trim());
                    return ResponseEntity.ok(noteRepository.save(n));
                })
                .orElse(ResponseEntity.notFound().build());
    }

    // ── DELETE note ──────────────────────────────────────────────────────
    /** DELETE /api/conversations/{id}/notes/{noteId} */
    @DeleteMapping("/{id}/notes/{noteId}")
    public ResponseEntity<Void> deleteNote(
            @PathVariable Long id,
            @PathVariable Long noteId) {
        noteRepository.findById(noteId)
                .filter(n -> n.getConversationId().equals(id))
                .ifPresent(noteRepository::delete);
        return ResponseEntity.noContent().build();
    }

    // ── AUTO-GENERATE notes for a specific date ──────────────────────────
    /**
     * POST /api/conversations/{id}/notes/generate?userId={userId}&date={yyyy-MM-dd}
     *
     * <p>Always re-runs extraction on all messages of the target day so that
     * new messages sent since the last generation are also captured.
     * Duplicate notes (same content prefix) are skipped before saving.
     */
    @PostMapping("/{id}/notes/generate")
    public ResponseEntity<List<Note>> generateNotes(
            @PathVariable Long id,
            @RequestParam Long userId,
            @RequestParam(required = false) String date) {

        LocalDate targetDate = (date != null) ? LocalDate.parse(date) : LocalDate.now();

        // Fetch text messages for the target day
        LocalDateTime from = targetDate.atStartOfDay();
        LocalDateTime to   = targetDate.atTime(LocalTime.MAX);
        List<Message> messages = messageRepository.findTextMessagesByDateRange(id, from, to);

        if (messages.isEmpty()) {
            log.info("📭 No messages for conv={} on {}", id, targetDate);
            return ResponseEntity.ok(
                    noteRepository.findByConversationIdAndUserIdOrderByCreatedAtAsc(id, userId));
        }

        // Build a set of already-saved auto-note content keys (first 40 chars) to avoid duplicates
        Set<String> existingKeys = noteRepository
                .findByConversationIdAndUserIdOrderByCreatedAtAsc(id, userId)
                .stream()
                .filter(n -> Boolean.TRUE.equals(n.getIsAutoGenerated()))
                .map(n -> n.getContent().toLowerCase().substring(0, Math.min(40, n.getContent().length())))
                .collect(Collectors.toCollection(HashSet::new));

        // Extract important points from all messages of the day
        List<ExtractedNote> extracted = extractionService.extract(messages);
        int newCount = 0;

        for (ExtractedNote en : extracted) {
            String key = en.content().toLowerCase().substring(0, Math.min(40, en.content().length()));
            if (existingKeys.contains(key)) continue;   // already saved, skip
            existingKeys.add(key);

            noteRepository.save(Note.builder()
                    .conversationId(id)
                    .userId(userId)
                    .content(en.content())
                    .isAutoGenerated(true)
                    .noteDate(en.timestamp().toLocalDate())
                    .sourceType(en.sourceType())
                    .build());
            newCount++;
        }

        log.info("✅ Generated {} new auto-notes for conv={} user={} date={} ({} messages analysed)",
                newCount, id, userId, targetDate, messages.size());

        return ResponseEntity.ok(
                noteRepository.findByConversationIdAndUserIdOrderByCreatedAtAsc(id, userId));
    }
}
