import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
import { environment } from '../../../environments/environment';

export interface ConversationNote {
  id: number;
  conversationId: number;
  userId: number;
  content: string;
  isAutoGenerated: boolean;
  noteDate: string;        // yyyy-MM-dd
  sourceType: string | null; // PAYMENT | DEADLINE | AGREEMENT | MEETING | DELIVERY | MILESTONE | null
  createdAt: string;
  updatedAt: string;
}

@Injectable({ providedIn: 'root' })
export class NoteService {

  private readonly base = environment.communicationApiBaseUrl;

  constructor(private http: HttpClient) {}

  getNotes(conversationId: number, userId: number): Observable<ConversationNote[]> {
    const params = new HttpParams().set('userId', userId.toString());
    return this.http.get<ConversationNote[]>(
      `${this.base}/api/conversations/${conversationId}/notes`, { params });
  }

  /**
   * Triggers smart auto-generation for a specific date (default: today).
   * Idempotent — safe to call every time the notes panel opens.
   */
  generateNotes(conversationId: number, userId: number, date?: string): Observable<ConversationNote[]> {
    let params = new HttpParams().set('userId', userId.toString());
    if (date) params = params.set('date', date);
    return this.http.post<ConversationNote[]>(
      `${this.base}/api/conversations/${conversationId}/notes/generate`, null, { params });
  }

  createNote(conversationId: number, userId: number, content: string): Observable<ConversationNote> {
    const params = new HttpParams().set('userId', userId.toString());
    return this.http.post<ConversationNote>(
      `${this.base}/api/conversations/${conversationId}/notes`, { content }, { params });
  }

  updateNote(conversationId: number, noteId: number, content: string): Observable<ConversationNote> {
    return this.http.put<ConversationNote>(
      `${this.base}/api/conversations/${conversationId}/notes/${noteId}`, { content });
  }

  deleteNote(conversationId: number, noteId: number): Observable<void> {
    return this.http.delete<void>(
      `${this.base}/api/conversations/${conversationId}/notes/${noteId}`);
  }
}
