package com.workify.communication.repository;

import com.workify.communication.domain.Note;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

@Repository
public interface NoteRepository extends JpaRepository<Note, Long> {

    /** All notes for a conversation (user-written + auto), ordered chronologically. */
    List<Note> findByConversationIdAndUserIdOrderByCreatedAtAsc(Long conversationId, Long userId);

    /** Check if auto-generated notes already exist for a specific date (idempotency guard). */
    boolean existsByConversationIdAndUserIdAndIsAutoGeneratedTrueAndNoteDate(
            Long conversationId, Long userId, LocalDate noteDate);

    /**
     * Returns all auto-generated notes for a conversation on a specific date.
     * Used by the scheduler to avoid regenerating.
     */
    @Query("SELECT n FROM Note n WHERE n.conversationId = :convId AND n.userId = :userId " +
           "AND n.isAutoGenerated = true AND n.noteDate = :date ORDER BY n.createdAt ASC")
    List<Note> findAutoNotesByDate(
            @Param("convId") Long conversationId,
            @Param("userId") Long userId,
            @Param("date") LocalDate date);

    /**
     * Returns distinct (conversationId, userId) pairs that have messages on a given date.
     * Used by the daily scheduler.
     */
    @Query("SELECT DISTINCT n.conversationId, n.userId FROM Note n WHERE n.noteDate = :date")
    List<Object[]> findDistinctConversationUserPairs(@Param("date") LocalDate date);
}
