package com.workify.communication.scheduler;

import com.workify.communication.domain.Message;
import com.workify.communication.domain.Note;
import com.workify.communication.repository.ConversationRepository;
import com.workify.communication.repository.MessageRepository;
import com.workify.communication.repository.NoteRepository;
import com.workify.communication.service.NoteExtractionService;
import com.workify.communication.service.NoteExtractionService.ExtractedNote;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

/**
 * Runs every day at 23:55 and generates auto-notes for all conversations
 * that had messages that day — covering cases where the Notes panel was never
 * opened by the user (so the on-demand endpoint was not called).
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DailyNoteScheduler {

    private final MessageRepository    messageRepository;
    private final NoteRepository       noteRepository;
    private final ConversationRepository conversationRepository;
    private final NoteExtractionService extractionService;

    @Scheduled(cron = "0 55 23 * * ?")   // every day at 23:55
    public void generateDailyNotes() {
        LocalDate today = LocalDate.now();
        LocalDateTime from = today.atStartOfDay();
        LocalDateTime to   = today.atTime(LocalTime.MAX);

        List<Long> activeConvIds = messageRepository.findActiveConversationIdsByDateRange(from, to);
        log.info("📅 DailyNoteScheduler: {} conversations active on {}", activeConvIds.size(), today);

        for (Long convId : activeConvIds) {
            processConversation(convId, today, from, to);
        }
    }

    private void processConversation(Long convId, LocalDate date,
                                     LocalDateTime from, LocalDateTime to) {
        // Determine both participants
        conversationRepository.findById(convId).ifPresent(conv -> {
            for (Long userId : List.of(conv.getCreatorId(), conv.getReceiverId())) {
                if (noteRepository.existsByConversationIdAndUserIdAndIsAutoGeneratedTrueAndNoteDate(
                        convId, userId, date)) {
                    continue;   // already generated for this user today
                }
                List<Message> messages = messageRepository.findTextMessagesByDateRange(convId, from, to);
                if (messages.isEmpty()) continue;

                List<ExtractedNote> extracted = extractionService.extract(messages);
                int count = 0;
                for (ExtractedNote en : extracted) {
                    noteRepository.save(Note.builder()
                            .conversationId(convId)
                            .userId(userId)
                            .content(en.content())
                            .isAutoGenerated(true)
                            .noteDate(en.timestamp().toLocalDate())
                            .sourceType(en.sourceType())
                            .build());
                    count++;
                }
                if (count > 0) {
                    log.info("✅ Scheduled: {} notes for conv={} user={}", count, convId, userId);
                }
            }
        });
    }
}
